"""
Generates a human-readable PR description explaining the CI/CD pipeline.
Uses Groq to produce markdown that becomes the PR body.
"""

import os
import logging
from groq import Groq
from dotenv import load_dotenv
from .prompts import load_prompt
from .yaml_generator import _format_structured_context

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))
logger = logging.getLogger(__name__)

# Use fast models — description is less critical than YAML correctness
MODELS = [
    "llama-3.3-70b-versatile",
    "meta-llama/llama-4-scout-17b-16e-instruct",
    "llama-3.1-8b-instant",
]


def generate_pr_description(ci_yaml: str, cd_yaml: str,
                            understanding: dict, structured: dict) -> str:
    """
    Generate a markdown PR body explaining the CI/CD pipeline.
    Falls back to a static description if all models fail.
    """
    system_prompt = load_prompt("pr_description", "system")
    user_message = load_prompt("pr_description", "user").format(
        structured_context=_format_structured_context(structured),
        core_idea=understanding.get("core_idea", "Unknown project"),
        ci_yaml=ci_yaml,
        cd_yaml=cd_yaml,
    )

    for model in MODELS:
        try:
            logger.info(f"  Generating PR description with {model}")
            response = client.chat.completions.create(
                model=model,
                max_tokens=2000,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_message},
                ],
                temperature=0.3,
            )
            body = response.choices[0].message.content.strip()

            # Strip markdown fences if model wrapped the whole thing
            if body.startswith("```"):
                body = body.split("```", 2)[1]
                if body.startswith("markdown"):
                    body = body[8:]
                body = body.strip()

            # Strip thinking tags
            if "<think>" in body:
                think_end = body.find("</think>")
                if think_end != -1:
                    body = body[think_end + 8:].strip()

            logger.info(f"  PR description generated ({len(body)} chars)")
            return body

        except Exception as e:
            logger.warning(f"  {model} failed for PR description: {e}")
            continue

    # Fallback — static but useful
    logger.warning("  All models failed — using fallback PR description")
    return _fallback_description(structured)


def _fallback_description(structured: dict) -> str:
    stack = structured.get("stack", "project")
    lines = [
        "## \U0001f680 Automated CI/CD Pipeline",
        "",
        f"This PR adds production-grade CI and CD workflows for this **{stack}** project, "
        "generated by [LynX](https://github.com/apps/lynx-ci-cd).",
        "",
        "### CI Pipeline (`.github/workflows/ci.yml`)",
        "- Triggers on push and pull requests to main",
        "- Sets up the language environment with version matrix",
        "- Caches dependencies for faster builds",
        "- Runs linting, tests, and build steps",
        "",
        "### CD Pipeline (`.github/workflows/cd.yml`)",
        "- Triggers automatically when CI passes on main",
        "- Uses deployment queueing (concurrency group)",
        "- Builds and packages the application",
        "- Deploys with health check verification",
        "",
        "### What to configure",
        "Set these repository secrets in **Settings > Secrets and variables > Actions**:",
        "- `DEPLOY_HOST` — Your deployment target",
        "- `DEPLOY_KEY` — SSH key or deployment token",
    ]
    return "\n".join(lines)
